' PULSE-SIEM_V1-TEST
$Regfile="m168def.dat"
$Crystal=20000000
$hwstack=40
$swstack=16
$framesize=32

CONFIG Pinb.0=OUTPUT
CONFIG PinB.2=INPUT
CONFIG PinB.3=INPUT
CONFIG PinB.4=INPUT
CONFIG PinB.5=INPUT
CONFIG PORTC=OUTPUT

PORTB.0=1

ABD:
IF PINB.2=0 THEN GOTO ABB
IF PINB.3=0 THEN GOTO ABB
IF PINB.4=0 THEN GOTO ABB
IF PINB.5=0 THEN GOTO ABB
TOGGLE PORTB.0
WAITMS 50
GOTO ABD
ABB:
WAITMS 50
GOTO ABB
